plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

base { archivesName = 'Sus_InstantSwap-3.0.0-Forge26.1' }

version = '3.0.0'
group = 'com.susinstantswap'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'susinstantswap'
        }
        register('client')
        register('server') { args '--nogui' }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.1-62.0.9')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        minecraft_version: '26.1',
        forge_version: '62.0.9',
        mod_id: 'susinstantswap',
        mod_version: '3.0.0',
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    archiveVersion = ''
    manifest {
        attributes([
            'Specification-Title': 'susinstantswap',
            'Specification-Version': '3.0.0',
            'Implementation-Title': "Su's Instant Swap",
            'Implementation-Version': '3.0.0',
            'MixinConfigs': 'susinstantswap.mixins.json'
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
