plugins {
    id 'java'
    id 'net.neoforged.moddev' version '1.0.0'
}

base { archivesName = 'Sus_InstantSwap-2.2.0-NF1.21.1' }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
    compileJava.options.encoding = 'UTF-8'
}

neoForge {
    version = project.neo_version
    runs { client { client() }; server { server() } }
    mods { susinstantswap { sourceSet(sourceSets.main) } }
    accessTransformers { file('src/main/resources/META-INF/accesstransformer.cfg') }
}

dependencies { annotationProcessor 'org.spongepowered:mixin:0.8.7:processor' }

jar { archiveVersion = '' }
