org.gradle.jvmargs=-Xmx2G -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

mod_version=3.0.0
maven_group=com.susinstantswap

fabric_api_version=0.145.1+26.1
modmenu_version=13.0.0
