org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
forge_version=61.1.8
forge_version_range=[61,)
loader_version_range=[61,)
mapping_channel=official
mapping_version=1.21.11

mod_id=susinstantswap
mod_name=Su's Instant Swap
mod_license=LGPL-3.0
mod_version=3.0.0
mod_group_id=com.susinstantswap
mod_authors=Su_Crispy
mod_description=Hold the inventory key to swap items with your hotbar. Coexists with vanilla.
