modLoader="javafml"
loaderVersion="[7,)"
license="LGPL-3.0"

[[mods]]
modId="susinstantswap"
version="3.0.0"
displayName="Su's Instant Swap"
logoFile="assets/susinstantswap/icon.png"
authors="Su_Crispy"
description='''Hold the inventory key to swap items with your hotbar. Coexists with vanilla.'''
clientSideOnly=true

[[mixins]]
config="susinstantswap.mixins.json"

[[dependencies.susinstantswap]]
    modId="forge"
    mandatory=true
    versionRange="[62,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.susinstantswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.2)"
    ordering="NONE"
    side="CLIENT"
