modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId="susinstantswap"
version="2.2.0"
displayName="Su's Instant Swap"
logoFile="assets/susinstantswap/icon.png"
authors="Su_Crispy"
description="Hold the inventory key to swap items with your hotbar. Coexists with vanilla."

[[mixins]]
config="susinstantswap.mixins.json"

[[dependencies.susinstantswap]]
modId="neoforge"
type="required"
versionRange="[21.0,21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.susinstantswap]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.2)"
ordering="NONE"
side="CLIENT"
